apiVersion: v1
kind: Pod
metadata:
  name: backend-pod
spec:
  containers:
  - name: backend
    image: noelmckeown/backend:v1  # This pulls from Docker Hub
    ports:
    - containerPort: 80
  imagePullSecrets:
  - name: regcred