apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
#      securityContext:
#        runAsNonRoot: true
      containers:
        - name: frontend
          image: noelmckeown/frontend:latest
          ports:
            - containerPort: 9000
          env:
            - name: BACKEND_HOST
              value: backend
            - name: BACKEND_PORT
              value: "8080"
            - name: FRONTEND_PORT
              value: "22137"
      imagePullSecrets:
      - name: regcred

#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: frontend
#spec:
#  type: LoadBalancer
#  selector:
#    app: frontend
#  ports:
#    - protocol: TCP
#      port: 80
#     targetPort: 22137
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 22137